### ISSUE TITLE
Date Pickers not visible

### ISSUE THREAD

**Issue by lduboeuf** [mateosalta/UUITK-gallery#10]
![screenshot20210207_004217820](https://user-images.githubusercontent.com/11663835/107132237-8c8c5400-68dd-11eb-8046-60186250b714.png)

**Comment by lduboeuf** [comment]
So that one is very weird. If you place a DatePicker component outside of an AdaptiveLayout ( e.g just as a child of MainView ), you will see the content of the picker, but not inside like it is now....
As well, if you use a Popup to display it, no pb.

**Comment by cibersheep** [comment]
Interesting...
